name: idara_plus
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.0
  intl: ^0.20.2
  screenshot: ^3.0.0
  path_provider: ^2.1.1
  share_plus: ^10.0.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.5
  pdf: ^3.10.0
  http: ^1.2.0  # add this line
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/

flutter_native_splash:
  color: "#ffffff"
  fullscreen: true
  android_12:
    color: "#ffffff"